services:
  web_app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "7755:7755"
    environment:
      FLASK_APP: core/server.py
    volumes:
      - .:/app
    command: bash run.sh